version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
# Puedes agregar el backend y la base de datos aquí después
